---
apiVersion: "extensions/v1beta1"
kind: "Deployment" 
spec: 
  replicas: 1
  template: 
    spec: 
      containers: 
      - env:
         - name: JAVA_OPTIONS
           value: "-Xmx256m"
         - name: AB_JOLOKIA_AUTH_OPENSHIFT
           value: "true"
         - name: AB_ENABLED
           value: "off"